# Generated by Django 3.1.6 on 2021-03-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
