# Generated by Django 3.1.6 on 2021-03-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210317_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
