# Generated by Django 3.1.6 on 2021-03-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210317_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='password',
            field=models.CharField(default='this is password', max_length=100),
        ),
    ]
