# Generated by Django 3.1.6 on 2021-03-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_token_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
